name: Update Daily Chart Data

on:
  schedule:
    - cron: '0 3 * * *'  # 3AM UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run updater script
        run: python updater.py

      - name: Commit and push if changed
        run: |
          git config user.name "chart-bot"
          git config user.email "chart-bot@users.noreply.github.com"
          git add chart_data/daily.json
          git commit -m "📈 Auto-update chart data" || echo "No changes"
          git push

